### ISSUE TITLE
Can not launch latest AppImage

### ISSUE THREAD

**Issue by ghost** [tyu1996/opera-AppImage#1]
**Build**: https://github.com/tyu1996/opera-AppImage/releases/download/continuous/Opera-.glibc2.16-x86_64.AppImage

**System**: Linux (Debian 9.x, x86_64)

### Terminal output

```
$ ./Opera-.glibc2.16-x86_64.AppImage
[5047:5047:0513/052147.116628:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /var/tmp/.mount_Opera-dJAwl7/usr/lib/x86_64-linux-gnu/opera/opera_sandbox is owned by root and has mode 4755.
Illegal instruction
```

Cast @probonopd

### Related

- https://github.com/glyphr-studio/Glyphr-Studio-Desktop/issues/42

**Comment by tyu1996** [comment]
Did you make the file executable?
> chmod +x ./Opera-.glibc2.16-x86_64.AppImage

**Comment by ghost** [comment]
> Did you make the file executable?

Of course.

**Comment by probonopd** [comment]
Try running with `--no-sandbox` and/or `--disable-namespace-sandbox `.

Reference:
https://github.com/johannesjo/super-productivity/issues/167

**Comment by probonopd** [comment]
Possibly related to https://github.com/electron/electron/issues/17972.

**Comment by tyu1996** [comment]
> Try running with `--no-sandbox` and/or `--disable-namespace-sandbox `.
> 
> Reference:
> [johannesjo/super-productivity#167](https://github.com/johannesjo/super-productivity/issues/167)

@Symbian9 does this solve the issue?

**Comment by ghost** [comment]
> does this solve the issue?

Yes, but it is a trick. So, it still a bug that should be fixed.

**Comment by tyu1996** [comment]
Issue solved with a command trick. More in depth bug-fix is unrelated here since it only meant for supplying unofficial Opera AppImage.
Closing the issue.
