### ISSUE TITLE
libcurl.so.4 missing, cannot launch

### ISSUE THREAD

**Issue by probonopd** [tyu1996/opera-AppImage#3]
On `ubuntu-mate-18.04-desktop-amd64.iso` cannot be started because a needed library is not bundled inside the AppImage:

![](https://user-images.githubusercontent.com/2480569/68155196-1ca45680-ff41-11e9-8ded-59ebe5c97d1a.png)

The general recommendation is to bundle every library that is not on the [excludelist](https://github.com/AppImage/pkg2appimage/blob/master/excludelist).

**Comment by tyu1996** [comment]
The library above did not come with Opera's own .deb package, so the above one will be an extra library to include in.

Is there any method/guide that I can include the library above during the process of pkg2appimage?

**Comment by probonopd** [comment]
Yes. _Theoretically_ pkg2appimage should detect such dependencies automatically, but it didn't catch this one because we didn't specify where to get dependencies from. I have updated the yml to do it, feel free to copy:

https://github.com/AppImage/pkg2appimage/blob/master/recipes/Opera.yml

Thanks for maintaining this project.

**Comment by tyu1996** [comment]
So I just knew the purpose of mentioning Ubuntu 'dist' inside yml.

I have already updated and built based on your opera yml script, and is inside the release section, mind to take a try on the latest build?

**Comment by probonopd** [comment]
It is missing the version string in the filename...

**Comment by tyu1996** [comment]
> It is missing the version string in the filename...

Fixed with naming schemes + modified the dist to Xenial (Opera no longer supports Trusty). It is now in releases. May try the latest build again, let me know if the issue on your Ubuntu Mate solved with this build.

**Comment by probonopd** [comment]
Thank you very much.
